### PR TITLE
Don't require conda command

### LINKED ISSUE #16: dirname: missing operand
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Running `byobu` gives me this error:
```
dirname: missing operand
Try 'dirname --help' for more information.
/home/ubuntu/micromamba/envs/ssx/bin/byobu: 35: .: cannot open //etc/profile.d/conda.sh: No such file
```

### Installed packages

```
List of packages in environment: "/home/ubuntu/micromamba/envs/byobu"

  Name              Version    Build               Channel    
────────────────────────────────────────────────────────────────
  _libgcc_mutex     0.1        conda_forge         conda-forge
  _openmp_mutex     4.5        2_gnu               conda-forge
  byobu             5.133      ha770c72_2          conda-forge
  bzip2             1.0.8      h7f98852_4          conda-forge
  ca-certificates   2023.7.22  hbcca054_0          conda-forge
  gettext           0.21.1     h27087fc_0          conda-forge
  ld_impl_linux-64  2.40       h41732ed_0          conda-forge
  libevent          2.1.10     h28343ad_4          conda-forge
  libexpat          2.5.0      hcb278e6_1          conda-forge
  libffi            3.4.2      h7f98852_5          conda-forge
  libgcc-ng         13.2.0     h807b86a_2          conda-forge
  libgomp           13.2.0     h807b86a_2          conda-forge
  libiconv          1.17       h166bdaf_0          conda-forge
  libnsl            2.0.0      hd590300_1          conda-forge
  libpng            1.6.39     h753d276_0          conda-forge
  libsqlite         3.43.0     h2797004_0          conda-forge
  libstdcxx-ng      13.2.0     h7e041cc_2          conda-forge
  libuuid           2.38.1     h0b41bf4_0          conda-forge
  libzlib           1.2.13     hd590300_5          conda-forge
  ncurses           6.4        hcb278e6_0          conda-forge
  newt              0.52.23    py311h459d7ec_2     conda-forge
  oniguruma         6.9.8      h166bdaf_0          conda-forge
  openssl           3.1.3      hd590300_0          conda-forge
  pcre              8.45       h9c3ff4c_0          conda-forge
  pip               23.2.1     pyhd8ed1ab_0        conda-forge
  popt              1.16       h0b475e3_2002       conda-forge
  python            3.11.5     hab00c5b_0_cpython  conda-forge
  python_abi        3.11       4_cp311             conda-forge
  readline          8.2        h8228510_1          conda-forge
  setuptools        68.2.2     pyhd8ed1ab_0        conda-forge
  slang             2.3.3      hac012bb_0          conda-forge
  tk                8.6.13     h2797004_0          conda-forge
  tmux              3.3        h385fc29_0          conda-forge
  tzdata            2023c      h71feb2d_0          conda-forge
  wheel             0.41.2     pyhd8ed1ab_0        conda-forge
  xz                5.2.6      h166bdaf_0          conda-forge
```

### Environment info

```
libmamba version : 1.5.1
     micromamba version : 1.5.1
           curl version : libcurl/7.88.1 OpenSSL/3.1.2 zlib/1.2.13 zstd/1.5.5 libssh2/1.11.0 nghttp2/1.52.0
     libarchive version : libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
       envs directories : /home/ubuntu/micromamba/envs
          package cache : /home/ubuntu/micromamba/pkgs
                          /home/ubuntu/.mamba/pkgs
            environment : byobu (active)
           env location : /home/ubuntu/micromamba/envs/byobu
      user config files : /home/ubuntu/.mambarc
 populated config files : /home/ubuntu/.condarc
       virtual packages : __unix=0=0
                          __linux=6.2.0=0
                          __glibc=2.35=0
                          __archspec=1=x86_64
                          __cuda=12.2=0
               channels : https://conda.anaconda.org/nvidia/linux-64
                          https://conda.anaconda.org/nvidia/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
       base environment : /home/ubuntu/micromamba
               platform : linux-64
```

### PR DESCRIPTION
**Pull request by matthiasdiener**
Fixes #16.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jerryc05** [comment]
just curious, how long will it take to propagate to the registry?

**Comment by jerryc05** [comment]
nvm propagated to registry now

**Comment by matthiasdiener** [comment]
> nvm propagated to registry now

Cool, is it fixed with the new package?

**Comment by jerryc05** [comment]
yes it worked

**Pull request merged**
